/**
 * Generates js/emoji-data.js from the GitHub gemoji database.
 * Usage: node tools/gen-emoji.cjs [path/to/emoji.json]
 */
const fs = require('fs');
const path = require('path');

const input = process.argv[2] || '/tmp/gemoji.json';
const data = JSON.parse(fs.readFileSync(input, 'utf8'));
const map = {};
let count = 0;

for (const e of data) {
  if (!e.emoji || !e.aliases) continue;
  for (const a of e.aliases) {
    const key = ':' + a + ':';
    if (!(key in map)) {
      map[key] = e.emoji;
      count++;
    }
  }
}

const header = `/**
 * Emoji shortcode database
 * Generated by tools/gen-emoji.cjs from GitHub gemoji (https://github.com/github/gemoji), MIT licensed.
 * Maps :shortcode: -> unicode emoji (${count} entries).
 */
window.EmojiData = `;
const body = JSON.stringify(map) + ';\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'emoji-data.js'), header + body, 'utf8');
console.log('entries:', count, 'size:', (fs.statSync(path.join(__dirname, '..', 'js', 'emoji-data.js')).size / 1024).toFixed(1) + 'KB');
